# version: "3.9"
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:6
#     ports:
#       - "27017:27017"

version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/bookstore
    command: ["npm", "start"]

volumes:
  mongo_data:
