version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: bookstore-app:${BUILD_NUMBER}
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/bookstore
    command: ["npm", "start"]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"   
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:




